name: Android 13 5.15
permissions:
  contents: write
  actions: write

on:
  workflow_dispatch: # Permet le lancement manuel (Bouton Bleu)
    inputs:
      make_release:
        description: 'Créer une Release GitHub ?'
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        description: 'Variante KernelSU (Next ou Legacy)'
        required: true
        type: string
        default: Next
      kernelsu_branch:
        description: 'Branche KernelSU'
        required: true
        type: string
        default: Stable
      version:
        description: 'Nom de la version (optionnel)'
        required: false
        type: string
        default: ""

jobs:
  build-kernel-a13-5-15-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          # --- AJOUT POUR TON PATCH DE NOVEMBRE 2025 ---
          - sub_level: "195" 
            os_patch_level: "2025-11"
          # ---------------------------------------------
          - sub_level: "189"
            os_patch_level: "2025-09"
          - sub_level: "180"
            os_patch_level: "2025-05"
          - sub_level: "178"
            os_patch_level: "2025-03"
          - sub_level: "170"
            os_patch_level: "2025-01"

    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release || false }}
      android_version: "android13"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant || 'Next' }}
      kernelsu_branch: ${{ inputs.kernelsu_branch || 'Stable' }}
      version: ${{ inputs.version || '' }}
      use_zram: true
      use_kpm: true
      BBG: false
