name: Android 13 5.15
permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      os_patch_level:
        required: true
        type: string
      make_release:
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        required: true
        type: string
        default: Next
      kernelsu_branch:
        required: true
        type: string
        default: Stable
      version:
        required: false
        type: string
        default: ""
      use_zram:
        required: true
        type: boolean
        default: true
      use_kpm:
        required: true
        type: boolean
        default: true
      BBG:
        required: true
        type: boolean
        default: false
  
jobs:
  build-kernel-a13-5-15-kernelsu-susfs:
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release || false }}
      android_version: "android13"
      kernel_version: "5.15"
      sub_level: "195"
      os_patch_level: ${{ inputs.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant || 'Next' }}
      kernelsu_branch: ${{ inputs.kernelsu_branch || 'Dev' }}
      version: ${{ inputs.version || '' }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}
      BBG: ${{ inputs.BBG || false }}
